version: "3.7"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    user: 1000:1000
    container_name: ${PROJECT_NAME}-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - docker-net-beeapps
    environment:
      MYSQL_ROOT_PASSWORD: ${PROJECT_NAME}
      MYSQL_USER: ${PROJECT_NAME}
      MYSQL_PASSWORD: ${PROJECT_NAME}
      MYSQL_DATABASE: ${PROJECT_NAME}

  web:
    image: nginx
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
      - 80:80
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-net-beeapps
    
  app:
    build: ./
    container_name: ${PROJECT_NAME}-app
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - ${SSH_PATH}:/root/.ssh
      - ./php.ini:/usr/local/etc/php/conf.d/base.ini
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    networks:
      - docker-net-beeapps
    environment:
      PHP_ENABLE_XDEBUG: 1
      MYSQL_PORT: ${MYSQL_PORT}
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
      TEST_RUNTIME_PATH: /tmp/runtime

networks:
  docker-net-beeapps:
    driver: 'bridge'
volumes:
  db-data: